### ISSUE TITLE
Error in test run

### ISSUE THREAD

**Issue by Andyargueasae** [a-h-b/binny#48] opened 2023-07-16 08:01 UTC
Hi,

So I was running tests by using the command:

./binny -l -n "TESTRUN" -r config/config.test.yaml

But after successfully running 7 jobs, the run of job 1: binny gives such following problems:
![image](https://github.com/a-h-b/binny/assets/88032525/fa696af9-ec9f-4c23-861f-ca663bb17cdd)

Seems that in the hdbscan.py in that conda environment, there is a typeerror for adding two built-in functions or methods, which is this line of code: 
<img width="565" alt="image" src="https://github.com/a-h-b/binny/assets/88032525/371be2c1-1e5e-4a04-91fd-225acdf9ab1f">

I don't know how to debug this.

Andy Tong from the University of Melbourne

**Comment by Andyargueasae** [comment] 2023-07-16 08:05
Here is the log for binny-log, it is empty.
[binning_binny.log](https://github.com/a-h-b/binny/files/12063519/binning_binny.log)

**Comment by ohickl** [comment] 2023-07-16 11:32
Hey Andy,

I could reproduce your error. It's probably because of this https://github.com/scikit-learn-contrib/hdbscan/issues/597. It will be fixed soon in the repo. In the meantime you can fix it by doing e.g.:

```
grep -i binny <my/path/to/binny/conda/envs>/*.yaml
# Activate the env thats called binny_linux
<conda/mamba/micromamba> <binny_linux_env_path>
<conda/mamba/micromamba> install -c conda-forge hdbscan=0.8.30
<conda/mamba/micromamba> deactivate
```

Let us know, if that works for you.

Best 
Oskar

**Comment by Andyargueasae** [comment] 2023-07-17 01:23
HI Oskar,

thanks for the advice. But I got some difficulty in activating the binny_linux environment. Does the line: <conda/mamba/micromamba> <binny_linux_env_path> mean mamba activate <binny_linux_env_path>?

**Comment by Andyargueasae** [comment] 2023-07-17 01:30
Hi Oskar,

Thanks for the advice. But I got the following problem:
<img width="809" alt="image" src="https://github.com/a-h-b/binny/assets/88032525/e059002e-857c-4c31-b473-7f26f26a5231">
Maybe my mamba version is too old.

**Comment by Andyargueasae** [comment] 2023-07-17 02:08
The conda version was 4.12.0 and was provided by the hpc platform. I've already reported this to the team when installing hdbscan=0.8.30 using conda.

**Comment by Andyargueasae** [comment] 2023-07-17 02:30
This is the log file I composed from mamba execution, seems that other errors were also haunting there.
[mamba.log](https://github.com/a-h-b/binny/files/12065677/mamba.log)

**Comment by Andyargueasae** [comment] 2023-07-17 03:34
Hi Oskar, just to let you know the problem was solved. Cheers!

**Closed** 2023-07-24 00:15 UTC
